[project]
name = "iocrr"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "keyring>=25.6.0",
    "pyyaml>=6.0.2",
    "requests>=2.32.3",
    "shodan>=1.31.0",
    "typer>=0.15.3",
]
