[project]
name = "iocrr"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "keyring>=25.6.0",
    "requests>=2.32.3",
    "shodan>=1.31.0",
]
